version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret

  mongodb-run-migrations:
    build:
      context: ./migrations
    environment:
      MONGO_URI: "mongodb://admin:secret@mongodb:27017/"
    depends_on:
      mongodb:
        condition: service_healthy
        
volumes:
  mongodb_data: 
